### ISSUE TITLE
App for cyber•Auction and GoT

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#196] opened 2019-02-12 08:21 UTC

**Comment by litvintech** [comment] 2019-02-25 08:06
I made the decision to made pure auction without direct connectivity to Aragon organization.
The workflow is to deploy contract, then transfer needed amount of CBD to this contract and after this eos style will auction start.

- [ ] auction contract
- [ ] testing environment
- [ ] tests

**Comment by xhipster** [comment] 2019-02-27 07:17
I believe it is what we need actually.

**Comment by xhipster** [comment] 2019-03-12 13:14
We designed with @asadovka the interface for auction.

**Comment by xhipster** [comment] 2019-09-10 14:00
Duplicate of #230

**Closed by xhipster** 2019-09-10 14:00 UTC
